#!/bin/bash

#qbittorrent:	.130
	#\	:3022 ssh
	#\	:3080 qbit webui
	#\	:3081 vlc webui

#emby		.131
	#\	:3122 ssh
	#\	:3196 emby webui

#omv		.132
	#\	:3222 ssh
	#\	:3280 omv webui

#git:		.133
	#\	:3322 ssh
	#\	:3324 gitweb

#LAMP:		.134
	#\	:3422 ssh
	#\	:3480 web

#Masquerade local subnet
sudo iptables -t nat -A POSTROUTING -s 192.168.100.0/24 -j MASQUERADE
sudo iptables -A FORWARD -o virbr0 -m state --state RELATED,ESTABLISHED -j ACCEPT
sudo iptables -A FORWARD -i virbr0 -o enp6s0 -j ACCEPT
sudo iptables -A FORWARD -i virbr0 -o lo -j ACCEPT

	
#enable port forwarding for vps machines in the same order than they appear
sudo iptables -I FORWARD -o virbr0 -d 192.168.100.130 -j ACCEPT
sudo iptables -I FORWARD -o virbr0 -d 192.168.100.131 -j ACCEPT
sudo iptables -I FORWARD -o virbr0 -d 192.168.100.132 -j ACCEPT
sudo iptables -I FORWARD -o virbr0 -d 192.168.100.133 -j ACCEPT
sudo iptables -I FORWARD -o virbr0 -d 192.168.100.134 -j ACCEPT

#port configuration
#xxyy
#xx= last two ip digits
#yy= common port

#ssh's
#qbit
sudo iptables -t nat -I PREROUTING -p tcp --dport 3022 -j DNAT --to 192.168.100.130:22
sudo iptables -t nat -I PREROUTING -p tcp --dport 3080 -j DNAT --to 192.168.100.130:3080
sudo iptables -t nat -I PREROUTING -p tcp --dport 3081 -j DNAT --to 192.168.100.130:3081

#emby
sudo iptables -t nat -I PREROUTING -p tcp --dport 3122 -j DNAT --to 192.168.100.131:22
sudo iptables -t nat -I PREROUTING -p tcp --dport 3196 -j DNAT --to 192.168.100.131:8096


#omv
sudo iptables -t nat -I PREROUTING -p tcp --dport 3222 -j DNAT --to  192.168.100.132:22
sudo iptables -t nat -I PREROUTING -p tcp --dport 3280 -j DNAT --to 192.168.100.132:80

#git
sudo iptables -t nat -I PREROUTING -p tcp --dport 3322 -j DNAT --to  192.168.100.133:22
sudo iptables -t nat -I PREROUTING -p tcp --dport 3324 -j DNAT --to 192.168.100.133:1234
sudo iptables -t nat -I PREROUTING -p tcp --dport 3380 -j DNAT --to 192.168.100.133:80

#LAMP
sudo iptables -t nat -I PREROUTING -p tcp --dport 3422 -j DNAT --to  192.168.100.134:22
sudo iptables -t nat -I PREROUTING -p tcp --dport 3480 -j DNAT --to 192.168.100.134:80
